# T-test

-- t-test is a statistical test used to determine whether there is a significant difference between the means (averages) of two groups

-- data = normal distributed

1. pop - mean

2.sample - mean and std

3.number of sample < 30

T-test = (sample mean - population mean) / (std sample/number of sample)

In [5]:
import scipy.stats as st
import numpy as np

In [6]:
t_table = st.t.ppf(0.05,24)
t_table

-1.7108820799094282

In [7]:
t_col = (80,75)/(np.sqrt((25/20)+(26/20)))
t_col

array([50.09794329, 46.96682183])

In [8]:
import scipy.stats as st

In [11]:
sam_x=90
p_u=82
p_std = 20
n = 81
ap = 0.05

In [10]:
z_cal = (sam_x - p_u)/ (p_std /np.sqrt(n))
z_cal

3.5999999999999996

In [13]:
z_table = st.norm.ppf(1-ap)
z_table

1.6448536269514722

In [15]:
if z_table < z_cal:
    print("ha is right :")
else:
    print("ho is right :")

ha is right :


Q.3

In [2]:
import scipy.stats as st
import numpy as np


In [3]:
t_table = st.t.ppf(1-0.025,19)
t_table

2.093024054408263

In [4]:
Before = np.array([50, 60, 45, 65, 55, 70, 40, 75, 80, 65, 70, 60, 50, 55, 45, 75, 60, 50, 65, 70])
After = np.array([60, 70, 55, 75, 65, 80, 50, 85, 90, 70, 75, 65, 55, 60, 50, 80, 65, 55, 70, 75])

In [5]:
std_a = np.std(After)
std_b = np.std(Before)
mean_a = np.mean(After)
mean_b = np.mean(Before)

In [6]:
t_cal = (mean_a - mean_b) / (np.sqrt(((std_a * std_a)/len(After))+((std_b*std_b)/len(Before))))
t_cal

2.061200527128206

# chi square test

-- applicable in two types of situations 

(1). goodness

(2). independence

In [7]:
import numpy as np

-- ob = objarbetion value

ex = expacted value

formula = (ob-ex)square/ex

In [8]:
ob = np.array([22,17,20,26,22,13])
ex = np.array([20,20,20,20,20,20])

In [9]:
np.sum(np.square(ob-ex)/ex)

5.1000000000000005

Q.2

-- A study was conducted to investigate whether there is a relationship between 
gender and the preferred genre of music. A sample of 235 people was selected,
and the data collected is shown below. Test at a 5% level of significance
whether there is a significant association between gender and music preference.

Gender	Pop	    HipHop	   Classical	Rock

Male	40	     45	        25 	         10

Female	35	     30	        20	         30

In [10]:
import numpy as np

In [11]:
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [16]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_row = np.array([sum_r1,sum_r2])
sum_row

array([120, 115])

In [13]:
sum_cal = row1 + row2
sum_cal

array([75, 75, 45, 40])

In [21]:
exp = []
for i in sum_row:
    for j in sum_cal:
        value = (i*j)/235
        exp.append(value)

In [22]:
obj = np.array([40,45,25,10,35,30,20,30])
obj

array([40, 45, 25, 10, 35, 30, 20, 30])

In [23]:
np.sum((np.square(obj-exp))/exp)

13.788747987117553